export type StockInfo = {
  ticker: string
  name: string
  market: "US" | "HK" | "CN"
  sector: string
  frequency: "monthly" | "quarterly" | "semi-annual" | "annual"
}

export const STOCK_DB: StockInfo[] = [
  { ticker: "AAPL", name: "苹果公司", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "MSFT", name: "微软公司", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "GOOGL", name: "谷歌", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "AMZN", name: "亚马逊", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "NVDA", name: "英伟达", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "META", name: "Meta", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "TSLA", name: "特斯拉", market: "US", sector: "汽车", frequency: "quarterly" },
  { ticker: "BRK.B", name: "伯克希尔", market: "US", sector: "金融", frequency: "annual" },
  { ticker: "JPM", name: "摩根大通", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "V", name: "Visa", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "MA", name: "万事达", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "JNJ", name: "强生公司", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "UNH", name: "联合健康", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "PFE", name: "辉瑞", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "ABBV", name: "艾伯维", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "MRK", name: "默沙东", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "KO", name: "可口可乐", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "PEP", name: "百事公司", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "PG", name: "宝洁公司", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "WMT", name: "沃尔玛", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "COST", name: "好市多", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "MCD", name: "麦当劳", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "NKE", name: "耐克", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "SBUX", name: "星巴克", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "O", name: "Realty Income", market: "US", sector: "REITs", frequency: "monthly" },
  { ticker: "AMT", name: "American Tower", market: "US", sector: "REITs", frequency: "quarterly" },
  { ticker: "PLD", name: "Prologis", market: "US", sector: "REITs", frequency: "quarterly" },
  { ticker: "EQIX", name: "Equinix", market: "US", sector: "REITs", frequency: "quarterly" },
  { ticker: "SPG", name: "Simon Property", market: "US", sector: "REITs", frequency: "quarterly" },
  { ticker: "T", name: "AT&T", market: "US", sector: "通信", frequency: "quarterly" },
  { ticker: "VZ", name: "Verizon", market: "US", sector: "通信", frequency: "quarterly" },
  { ticker: "NEE", name: "NextEra Energy", market: "US", sector: "公用事业", frequency: "quarterly" },
  { ticker: "DUK", name: "Duke Energy", market: "US", sector: "公用事业", frequency: "quarterly" },
  { ticker: "SO", name: "Southern Company", market: "US", sector: "公用事业", frequency: "quarterly" },
  { ticker: "D", name: "Dominion Energy", market: "US", sector: "公用事业", frequency: "quarterly" },
  { ticker: "XOM", name: "埃克森美孚", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "CVX", name: "雪佛龙", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "COP", name: "ConocoPhillips", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "IBM", name: "IBM", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "TXN", name: "德州仪器", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "HD", name: "家得宝", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "CAT", name: "卡特彼勒", market: "US", sector: "工业", frequency: "quarterly" },
  { ticker: "MMM", name: "3M", market: "US", sector: "工业", frequency: "quarterly" },
  { ticker: "LIN", name: "林德", market: "US", sector: "工业", frequency: "quarterly" },
  { ticker: "BMY", name: "百时美施贵宝", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "TMO", name: "赛默飞", market: "US", sector: "医疗", frequency: "quarterly" },
  { ticker: "CRM", name: "Salesforce", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "ORCL", name: "甲骨文", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "ADBE", name: "Adobe", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "INTC", name: "英特尔", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "CSCO", name: "思科", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "QCOM", name: "高通", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "AVGO", name: "博通", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "AMD", name: "AMD", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "MU", name: "美光科技", market: "US", sector: "科技", frequency: "quarterly" },
  { ticker: "LMT", name: "洛克希德马丁", market: "US", sector: "国防", frequency: "quarterly" },
  { ticker: "RTX", name: "雷神技术", market: "US", sector: "国防", frequency: "quarterly" },
  { ticker: "BA", name: "波音", market: "US", sector: "国防", frequency: "quarterly" },
  { ticker: "GS", name: "高盛", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "MS", name: "摩根士丹利", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "BLK", name: "贝莱德", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "C", name: "花旗集团", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "WFC", name: "富国银行", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "BAC", name: "美国银行", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "USB", name: "US Bancorp", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "TGT", name: "塔吉特", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "CL", name: "高露洁", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "KMB", name: "金佰利", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "GIS", name: "通用磨坊", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "KHC", name: "卡夫亨氏", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "HSY", name: "好时", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "HRL", name: "Hormel Foods", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "SYY", name: "Sysco", market: "US", sector: "消费", frequency: "quarterly" },
  { ticker: "STAG", name: "STAG Industrial", market: "US", sector: "REITs", frequency: "monthly" },
  { ticker: "WPC", name: "W. P. Carey", market: "US", sector: "REITs", frequency: "quarterly" },
  { ticker: "OHI", name: "Omega Healthcare", market: "US", sector: "REITs", frequency: "monthly" },
  { ticker: "AGNC", name: "AGNC Investment", market: "US", sector: "REITs", frequency: "monthly" },
  { ticker: "NLY", name: "Annaly Capital", market: "US", sector: "REITs", frequency: "quarterly" },
  { ticker: "EPD", name: "Enterprise Products", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "ET", name: "Energy Transfer", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "MMP", name: "Magellan Midstream", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "PBA", name: "Pembina Pipeline", market: "US", sector: "能源", frequency: "monthly" },
  { ticker: "ENB", name: "Enbridge", market: "US", sector: "能源", frequency: "quarterly" },
  { ticker: "BNS", name: "Bank of Nova Scotia", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "RY", name: "Royal Bank of Canada", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "TD", name: "Toronto-Dominion", market: "US", sector: "金融", frequency: "quarterly" },
  { ticker: "BCE", name: "BCE Inc", market: "US", sector: "通信", frequency: "quarterly" },
  { ticker: "TU", name: "Telus", market: "US", sector: "通信", frequency: "quarterly" },
  { ticker: "0001.HK", name: "长和", market: "HK", sector: "综合", frequency: "annual" },
  { ticker: "0002.HK", name: "中电控股", market: "HK", sector: "公用事业", frequency: "semi-annual" },
  { ticker: "0003.HK", name: "香港中华煤气", market: "HK", sector: "公用事业", frequency: "semi-annual" },
  { ticker: "0005.HK", name: "汇丰控股", market: "HK", sector: "金融", frequency: "quarterly" },
  { ticker: "0006.HK", name: "电能实业", market: "HK", sector: "公用事业", frequency: "semi-annual" },
  { ticker: "0011.HK", name: "恒生银行", market: "HK", sector: "金融", frequency: "semi-annual" },
  { ticker: "0012.HK", name: "恒基地产", market: "HK", sector: "地产", frequency: "semi-annual" },
  { ticker: "0016.HK", name: "新鸿基地产", market: "HK", sector: "地产", frequency: "semi-annual" },
  { ticker: "0017.HK", name: "新世界发展", market: "HK", sector: "地产", frequency: "semi-annual" },
  { ticker: "0066.HK", name: "港铁公司", market: "HK", sector: "交通", frequency: "semi-annual" },
  { ticker: "0101.HK", name: "恒隆集团", market: "HK", sector: "地产", frequency: "semi-annual" },
  { ticker: "0267.HK", name: "中信股份", market: "HK", sector: "综合", frequency: "annual" },
  { ticker: "0386.HK", name: "中国石化", market: "HK", sector: "能源", frequency: "semi-annual" },
  { ticker: "0388.HK", name: "香港交易所", market: "HK", sector: "金融", frequency: "semi-annual" },
  { ticker: "0700.HK", name: "腾讯控股", market: "HK", sector: "科技", frequency: "annual" },
  { ticker: "0941.HK", name: "中国移动", market: "HK", sector: "通信", frequency: "semi-annual" },
  { ticker: "0939.HK", name: "建设银行", market: "HK", sector: "金融", frequency: "annual" },
  { ticker: "1398.HK", name: "工商银行", market: "HK", sector: "金融", frequency: "annual" },
  { ticker: "2318.HK", name: "中国平安", market: "HK", sector: "金融", frequency: "annual" },
  { ticker: "2388.HK", name: "中银香港", market: "HK", sector: "金融", frequency: "annual" },
  { ticker: "3988.HK", name: "中国银行", market: "HK", sector: "金融", frequency: "annual" },
  { ticker: "600519.SH", name: "贵州茅台", market: "CN", sector: "消费", frequency: "annual" },
  { ticker: "601318.SH", name: "中国平安", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "600036.SH", name: "招商银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "601166.SH", name: "兴业银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "600900.SH", name: "长江电力", market: "CN", sector: "公用事业", frequency: "annual" },
  { ticker: "601088.SH", name: "中国神华", market: "CN", sector: "能源", frequency: "annual" },
  { ticker: "600028.SH", name: "中国石化", market: "CN", sector: "能源", frequency: "semi-annual" },
  { ticker: "601398.SH", name: "工商银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "601939.SH", name: "建设银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "600000.SH", name: "浦发银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "601288.SH", name: "农业银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "600016.SH", name: "民生银行", market: "CN", sector: "金融", frequency: "annual" },
  { ticker: "000858.SZ", name: "五粮液", market: "CN", sector: "消费", frequency: "annual" },
  { ticker: "000333.SZ", name: "美的集团", market: "CN", sector: "消费", frequency: "annual" },
  { ticker: "000651.SZ", name: "格力电器", market: "CN", sector: "消费", frequency: "annual" },
  { ticker: "600887.SH", name: "伊利股份", market: "CN", sector: "消费", frequency: "annual" },
  { ticker: "002304.SZ", name: "洋河股份", market: "CN", sector: "消费", frequency: "annual" },
  { ticker: "600585.SH", name: "海螺水泥", market: "CN", sector: "工业", frequency: "annual" },
  { ticker: "601899.SH", name: "紫金矿业", market: "CN", sector: "能源", frequency: "annual" },
]

export function searchStocks(query: string, market?: string): StockInfo[] {
  if (!query || query.length < 1) return []
  const q = query.toUpperCase()
  return STOCK_DB.filter((s) => {
    if (market && s.market !== market) return false
    return s.ticker.toUpperCase().includes(q) || s.name.toUpperCase().includes(q)
  }).slice(0, 8)
}
